version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - java -version
      - mvn package -DskipTests
artifacts:
  files:
    - '**/*'
  base-directory: 'target'